### ISSUE TITLE
Figma/Maс OS/ Issue

### ISSUE THREAD

**Issue by vkatasonov** [wr/figma-mac#4]
Hey everybody. Can you help me pls. I have an issue with figma on my late-2011 MacBook Pro. Everything was ok until latest updates. In browser works fine, especially in Firefox, but desktop app makes crazy things like black squares on the screen and stuff like this. I reproduced issue in Chrome enabling #ignore-gpu-blocklist at chrome:flags section. But unfortunately I don't know how to disable that stuff in native figma app to make it work "great again" (c)=))))

**Comment by vkatasonov** [comment]
Data exported | 2021-04-15T17:34:13.029Z
-- | --
Chrome version | Chrome/90.0.4430.72
Operating system | Mac OS X 10.13.6
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/b6172ef8d07ef486489a4b11b66b2eaeed50d132/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/b6172ef8d07ef486489a4b11b66b2eaeed50d132/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 0297dd80c5d2
2D graphics backend | Skia/90 d9182fe43730b84d59598f460319930eefdaeca7
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_90134 --flag-switches-begin --enable-nacl --enable-webgl-draft-extensions --enable-features=UseSkiaRenderer --flag-switches-end --origin-trial-disabled-features=SecurePaymentConfirmation

**Comment by wr** [comment]
Sorry, but this project was deprecated when Figma released their own official desktop app. You should reach out to their support if you're having trouble with it! https://help.figma.com/hc/en-us

**Comment by vkatasonov** [comment]
i tried with a very bad luck... I've been told that there is nothing to do. I mean that the issue had been reproduced in Chrome and if it ignores gpu blocklist it could be probably disabled. I wish I knew how...
